general:
  pages_dir: "./pages"
  index: home
  host: "127.0.0.1"
  debug: True
  secret_key_path: "./key.txt"

sign-in:
  question: "Write test"
  password: "test"

history:
  folder: "./pages/history"
  file: "data-"

pages:
  - home
  - year-1
  - year-2
  - year-3
  - year-4
  - year-5
